# Generated by Django 4.2.1 on 2023-05-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='user',
        ),
    ]
