# Generated by Django 4.2.1 on 2023-05-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippetapp', '0003_snippet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snippetapp.tag'),
        ),
    ]
