# Generated by Django 4.2.1 on 2023-05-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippetapp', '0006_alter_snippet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='tags',
        ),
        migrations.AddField(
            model_name='snippet',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='snippetapp.tag'),
        ),
    ]
