# Generated by Django 4.2.1 on 2023-05-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippetapp', '0008_rename_tag_snippet_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='tags',
            new_name='tag',
        ),
    ]
